openstackclient: set CFLAGS="-Wno-int-conversion"
This solves the following problem. It can be removed in the future if
netifaces is no longer used as a dependency of the OpenStack SDK.

netifaces.c:1808:9: error: initialization of 'int' from 'void *' makes
integer from pointer without a cast [-Wint-conversion]

Signed-off-by: Christian Berendt <berendt@osism.tech>